# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: keyvalue.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'keyvalue.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekeyvalue.proto\x12\x08keyvalue\"(\n\nSetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x1e\n\x0bSetResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x19\n\nGetRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"+\n\x0bGetResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\x0c\"7\n\x10GetPrefixRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x13\n\x0bmax_results\x18\x02 \x01(\x03\"*\n\x0cKeyValuePair\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\":\n\x11GetPrefixResponse\x12%\n\x05pairs\x18\x01 \x03(\x0b\x32\x16.keyvalue.KeyValuePair\"\r\n\x0bStatRequest\"\x93\x01\n\x0cStatResponse\x12\x11\n\tkey_count\x18\x01 \x01(\x03\x12\x19\n\x11server_start_time\x18\x02 \x01(\t\x12\x16\n\x0etotal_requests\x18\x03 \x01(\x03\x12\x11\n\tset_count\x18\x04 \x01(\x03\x12\x11\n\tget_count\x18\x05 \x01(\x03\x12\x17\n\x0fgetprefix_count\x18\x06 \x01(\x03\x32\xf7\x01\n\x08KeyValue\x12\x34\n\x03Set\x12\x14.keyvalue.SetRequest\x1a\x15.keyvalue.SetResponse\"\x00\x12\x34\n\x03Get\x12\x14.keyvalue.GetRequest\x1a\x15.keyvalue.GetResponse\"\x00\x12\x46\n\tGetPrefix\x12\x1a.keyvalue.GetPrefixRequest\x1a\x1b.keyvalue.GetPrefixResponse\"\x00\x12\x37\n\x04Stat\x12\x15.keyvalue.StatRequest\x1a\x16.keyvalue.StatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyvalue_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETREQUEST']._serialized_start=28
  _globals['_SETREQUEST']._serialized_end=68
  _globals['_SETRESPONSE']._serialized_start=70
  _globals['_SETRESPONSE']._serialized_end=100
  _globals['_GETREQUEST']._serialized_start=102
  _globals['_GETREQUEST']._serialized_end=127
  _globals['_GETRESPONSE']._serialized_start=129
  _globals['_GETRESPONSE']._serialized_end=172
  _globals['_GETPREFIXREQUEST']._serialized_start=174
  _globals['_GETPREFIXREQUEST']._serialized_end=229
  _globals['_KEYVALUEPAIR']._serialized_start=231
  _globals['_KEYVALUEPAIR']._serialized_end=273
  _globals['_GETPREFIXRESPONSE']._serialized_start=275
  _globals['_GETPREFIXRESPONSE']._serialized_end=333
  _globals['_STATREQUEST']._serialized_start=335
  _globals['_STATREQUEST']._serialized_end=348
  _globals['_STATRESPONSE']._serialized_start=351
  _globals['_STATRESPONSE']._serialized_end=498
  _globals['_KEYVALUE']._serialized_start=501
  _globals['_KEYVALUE']._serialized_end=748
# @@protoc_insertion_point(module_scope)
